
db.driver=com.mysql.jdbc.Driver
db.url=jdbc:mysql://${dbhostname}:3306/${dbname}
db.username=${dbuser}
db.password=${dbpassword}

 
#Hibernate Configuration
hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.hbm2ddl.auto=update
hibernate.ejb.naming_strategy=org.hibernate.cfg.ImprovedNamingStrategy
hibernate.show_sql=true
hibernate.format_sql=true

SerializationFeature.write-dates-as-timestamps=true
spring.main.allow-circular-references=true
logging.level.com.runcible.abbot=DEBUG
logging.level.org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.security.web.CsrfFilter=DEBUG
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.web=TRACE
logging.level.org.springframework.security.web.csrf=DEBUG

# TLS Configuration
# enable/disable https
server.port=${server_port}
server.ssl.enabled=${enable_ssl}
server.ssl.key-store-type=PKCS12
server.ssl.key-store=/certs/keystore.p12
server.ssl.key-store-password=changeit
server.ssl.protocol=TLS
server.ssl.enabled-protocols=TLSv1.3

app.cors.allowed-origins=${domain},http://localhost:8443
